name: user_map_trace_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.3.0
  dio: ^5.9.0
  flutter_svg: ^2.2.3
  flutter_cache_manager: ^3.4.1
  get_it: ^9.2.0
  equatable: ^2.0.7
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.3
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  auto_route: ^11.1.0
  lottie: ^3.3.2
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  flutter_background_service: ^5.1.0
  geocoding: ^4.0.0
  permission_handler: ^12.0.1
  latlong2: ^0.9.1

  orange_sdk:
    git:
      url: https://github.com/dogukanozgurylmz/orange-sdk
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_ce_generator: ^1.11.0
  build_runner: ^2.10.4
  auto_route_generator: ^10.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/markers/
